### ISSUE TITLE
源代码还不完善

### ISSUE THREAD

**Issue by WinterXMQ** [binbinstrong/tangsengjiewa#2]
1. `RevitHelper` 和  `WinHelper` 不存在
在 `BinLibrary->Extension` 的 `TransactionHelper` 中引用了 `RevitHelper` 和  `WinHelper`，使用 `LogHelper`
![11](https://user-images.githubusercontent.com/3694982/56714380-39c4c500-6767-11e9-8da4-77ebeb32edd2.png)
2.  我使用了 2017版本的 `RevitAPI.dll`，提示有部分API不支持
![image](https://user-images.githubusercontent.com/3694982/56715998-c83b4580-676b-11e9-876f-b4d152eca2ac.png)
![image](https://user-images.githubusercontent.com/3694982/56716032-dab57f00-676b-11e9-98ac-eb5fdccf6b4b.png)

**Comment by binbinstrong** [comment]
now it is completed!

**Comment by binbinstrong** [comment]
learn and try it!
